export const siteConfig = {
  name: "Lotus Kidney & Andrology Center",
  description: "Expert kidney, urology, and andrology care in Hyderabad. Dr. Nitesh Battala offers advanced treatments including kidney stone laser treatment, prostate care, male infertility, robotic surgery, and renal transplantation.",
  url: "https://www.lotuskidneyandrology.in",
  ogImage: "https://www.lotuskidneyandrology.in/LOTUS-LOGO.png",
  links: {
    whatsapp: "https://wa.me/917093070434",
    googleMaps: "https://maps.app.goo.gl/1FDGzNzzPgBuaPoF7",
  },
  contact: {
    email: "lkac@gmail.com",
    phone: "+917093070434",
    phone2: "+919502926710",
    address: {
      street: "Uppal",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500039",
      country: "India",
    },
  },
  businessHours: {
    display: "Mon–Sat: 9:00 AM – 9:00 PM",
    schema: [
      { day: "Monday", opens: "09:00", closes: "21:00" },
      { day: "Tuesday", opens: "09:00", closes: "21:00" },
      { day: "Wednesday", opens: "09:00", closes: "21:00" },
      { day: "Thursday", opens: "09:00", closes: "21:00" },
      { day: "Friday", opens: "09:00", closes: "21:00" },
      { day: "Saturday", opens: "09:00", closes: "21:00" },
    ],
  },
  doctor: {
    name: "Dr. Nitesh Battala",
    qualifications: "MBBS, MS (General Surgery), DrNB (Urology)",
    title: "Consultant Urologist, Andrologist, Uro Oncologist, Renal Transplant & Robotic Surgeon",
  },
  keywords: [
    // Primary Keywords - Urologist
    "best urologist in Hyderabad",
    "urologist in Hyderabad",
    "urologist near me",
    "best urologist near me",
    "top urologist in Hyderabad",
    "urologist in Uppal",
    "urologist in Uppal Hyderabad",
    "best urologist in Uppal",
    "urologist near Uppal",
    "urologist in Medchal",
    "urologist in LB Nagar",
    "urologist in Secunderabad",
    "urologist in Nagole",
    "urologist in Habsiguda",
    "urologist in Ramanthapur",
    "urologist in Tarnaka",
    "urologist in Chilkalguda",
    "famous urologist in Hyderabad",
    "experienced urologist in Hyderabad",
    
    // Kidney Specialist Keywords
    "kidney specialist in Hyderabad",
    "best kidney specialist in Hyderabad",
    "kidney doctor in Hyderabad",
    "kidney specialist near me",
    "best kidney doctor near me",
    "kidney specialist in Uppal",
    "kidney doctor in Uppal",
    "kidney specialist in Medchal",
    "kidney specialist in LB Nagar",
    "kidney specialist in Secunderabad",
    "nephrologist in Hyderabad",
    "best kidney specialist in Telangana",
    
    // Andrology Specialist Keywords
    "andrology specialist in Hyderabad",
    "andrologist in Hyderabad",
    "best andrologist in Hyderabad",
    "andrology doctor in Hyderabad",
    "andrologist near me",
    "best andrology specialist near me",
    "andrologist in Uppal",
    "male fertility specialist in Hyderabad",
    "men's health specialist in Hyderabad",
    
    // Kidney Stone Treatment Keywords
    "kidney stone treatment in Hyderabad",
    "best kidney stone treatment in Hyderabad",
    "kidney stone specialist in Hyderabad",
    "kidney stone doctor in Hyderabad",
    "kidney stone removal in Hyderabad",
    "kidney stone laser treatment in Hyderabad",
    "kidney stone treatment near me",
    "best kidney stone doctor near me",
    "kidney stone surgery in Hyderabad",
    "PCNL surgery in Hyderabad",
    "RIRS procedure in Hyderabad",
    "URSL treatment in Hyderabad",
    "ESWL treatment in Hyderabad",
    "laser treatment for kidney stones Hyderabad",
    "kidney stone hospital in Hyderabad",
    "kidney stone clinic near me",
    "kidney stone specialist in Uppal",
    "kidney stone treatment in Uppal",
    "kidney stone doctor in Medchal",
    "kidney stone removal near me",
    "painless kidney stone treatment Hyderabad",
    
    // Prostate Treatment Keywords
    "prostate treatment in Hyderabad",
    "best prostate treatment in Hyderabad",
    "prostate specialist in Hyderabad",
    "prostate doctor in Hyderabad",
    "prostate problem treatment near me",
    "BPH treatment in Hyderabad",
    "enlarged prostate treatment Hyderabad",
    "prostate surgery in Hyderabad",
    "TURP surgery in Hyderabad",
    "prostate cancer treatment in Hyderabad",
    "prostate specialist near me",
    "best prostate doctor in Hyderabad",
    "prostate treatment in Uppal",
    "prostatitis treatment in Hyderabad",
    
    // Male Infertility Keywords
    "male infertility treatment in Hyderabad",
    "best male infertility specialist in Hyderabad",
    "male infertility doctor in Hyderabad",
    "male fertility clinic in Hyderabad",
    "male infertility treatment near me",
    "infertility specialist for men Hyderabad",
    "male fertility doctor near me",
    "low sperm count treatment Hyderabad",
    "azoospermia treatment in Hyderabad",
    "male infertility clinic in Uppal",
    "best male infertility doctor near me",
    
    // Erectile Dysfunction Keywords
    "erectile dysfunction treatment in Hyderabad",
    "ED treatment in Hyderabad",
    "best ED doctor in Hyderabad",
    "erectile dysfunction specialist Hyderabad",
    "ED treatment near me",
    "impotence treatment in Hyderabad",
    "erectile dysfunction doctor near me",
    "best erectile dysfunction specialist near me",
    "ED clinic in Hyderabad",
    "erectile dysfunction treatment in Uppal",
    
    // Premature Ejaculation Keywords
    "premature ejaculation treatment in Hyderabad",
    "PE treatment in Hyderabad",
    "premature ejaculation doctor Hyderabad",
    "PE specialist near me",
    "premature ejaculation treatment near me",
    "best PE doctor in Hyderabad",
    
    // Male Sexual Health Keywords
    "male sexual health specialist Hyderabad",
    "men's sexual health clinic Hyderabad",
    "sexual health doctor for men near me",
    "male sexual problems treatment Hyderabad",
    "sexologist in Hyderabad",
    "best sexologist in Hyderabad",
    
    // UTI Treatment Keywords
    "UTI treatment in Hyderabad",
    "urinary tract infection treatment Hyderabad",
    "UTI doctor in Hyderabad",
    "urinary infection specialist near me",
    "recurrent UTI treatment Hyderabad",
    "UTI specialist in Hyderabad",
    "best UTI doctor near me",
    
    // Circumcision Keywords
    "circumcision surgery in Hyderabad",
    "circumcision in Hyderabad",
    "best circumcision doctor in Hyderabad",
    "adult circumcision in Hyderabad",
    "pediatric circumcision Hyderabad",
    "circumcision near me",
    "circumcision surgery near me",
    "best circumcision surgeon Hyderabad",
    "circumcision in Uppal",
    "safe circumcision surgery Hyderabad",
    "laser circumcision in Hyderabad",
    
    // Pediatric Urology Keywords
    "pediatric urologist in Hyderabad",
    "best pediatric urologist in Hyderabad",
    "children urologist in Hyderabad",
    "pediatric urology specialist Hyderabad",
    "child urologist near me",
    "bedwetting treatment in Hyderabad",
    "pediatric kidney specialist Hyderabad",
    "children UTI treatment Hyderabad",
    
    // Uro-Oncology Keywords
    "uro oncologist in Hyderabad",
    "urological cancer treatment Hyderabad",
    "bladder cancer treatment in Hyderabad",
    "kidney cancer treatment in Hyderabad",
    "prostate cancer specialist Hyderabad",
    "cancer urologist in Hyderabad",
    "uro oncology specialist near me",
    "best uro oncologist in Hyderabad",
    
    // Kidney Transplant Keywords
    "kidney transplant in Hyderabad",
    "renal transplant in Hyderabad",
    "kidney transplant surgeon in Hyderabad",
    "best kidney transplant doctor Hyderabad",
    "kidney transplant specialist near me",
    "renal transplantation in Hyderabad",
    "kidney transplant hospital Hyderabad",
    
    // Robotic Surgery Keywords
    "robotic urology surgery in Hyderabad",
    "robotic kidney surgery Hyderabad",
    "robotic prostate surgery Hyderabad",
    "robotic urologist in Hyderabad",
    "laparoscopic urology surgery Hyderabad",
    "minimally invasive urology Hyderabad",
    "best robotic surgeon in Hyderabad",
    
    // Reconstructive Urology Keywords
    "urethral stricture treatment in Hyderabad",
    "urethroplasty in Hyderabad",
    "reconstructive urologist Hyderabad",
    "urethral surgery in Hyderabad",
    "buccal mucosal graft surgery Hyderabad",
    
    // Incontinence Keywords
    "urinary incontinence treatment Hyderabad",
    "urine leakage treatment in Hyderabad",
    "bladder control problems treatment Hyderabad",
    "incontinence specialist in Hyderabad",
    "urine leak doctor near me",
    
    // General Location-Based Keywords
    "urology clinic in Hyderabad",
    "best urology clinic in Hyderabad",
    "urology hospital in Hyderabad",
    "kidney clinic in Hyderabad",
    "andrology clinic in Hyderabad",
    "urology clinic near me",
    "kidney hospital near me",
    "urology clinic in Uppal",
    "kidney clinic in Uppal",
    "urology hospital in Uppal",
    "best urology hospital in Hyderabad",
    "private urologist in Hyderabad",
    
    // Specific Procedure Keywords
    "TURP surgery in Hyderabad",
    "TURBT surgery in Hyderabad",
    "cystoscopy in Hyderabad",
    "vasectomy in Hyderabad",
    "vasectomy reversal in Hyderabad",
    "varicocele surgery in Hyderabad",
    "hydrocele surgery in Hyderabad",
    "pyeloplasty in Hyderabad",
    "nephrectomy in Hyderabad",
    
    // Emergency & Urgent Care Keywords
    "emergency urologist in Hyderabad",
    "24 hour urologist near me",
    "urgent urology care Hyderabad",
    "kidney stone emergency Hyderabad",
    
    // Consultation Keywords
    "urologist consultation in Hyderabad",
    "kidney specialist consultation near me",
    "online urology consultation Hyderabad",
    "teleconsultation urologist Hyderabad",
    
    // Doctor Specific Keywords
    "Dr Nitesh Battala",
    "Dr Battala Nitesh urologist",
    "Dr Nitesh Battala Hyderabad",
    "Dr Battala urologist",
    
    // Nearby Areas Keywords
    "urologist in Kushaiguda",
    "urologist in Nacharam",
    "urologist in ECIL",
    "urologist in AS Rao Nagar",
    "urologist in Malkajgiri",
    "urologist in Boudha Nagar",
    "urologist in Peerzadiguda",
    "urologist in Ghatkesar",
    "kidney specialist in Kushaiguda",
    "kidney specialist in Nacharam",
    "kidney specialist in ECIL",
    "kidney doctor in Malkajgiri",
    
    // Question-Based Keywords (Featured Snippets)
    "how to treat kidney stones",
    "kidney stone symptoms",
    "causes of kidney stones",
    "what causes frequent urination",
    "prostate enlargement symptoms",
    "BPH treatment options",
    "male infertility causes",
    "erectile dysfunction treatment options",
    "when to see a urologist",
    "kidney pain causes",
  ],
}

